### ISSUE TITLE
Dependency will works on both iOS and Android

### ISSUE THREAD

**Issue by mahipalsingh7** [emilemoureau/react-native-screen-recorder-detect#2]
I have application for both ios and android . So this dependency will works for both iOS and Android?

**Comment by emilemoureau** [comment]
It will only work on iOS, I should publish the Android version in maximum two weeks! And then create a real module!

**Comment by binbingol** [comment]
Hi. Wondering if the Android version is working..?

**Comment by kazzkiq** [comment]
Hi. Are there still plans to publish an Android version?

**Comment by babitakapoor112** [comment]
Hi, Is this library is used to record the screen or just detecting it?

**Comment by emilemoureau** [comment]
Hi! Just detect!

**Comment by jhanzaibkhadim199** [comment]
Not detecting anything on ios 16. also no errors. Can you help ?
